name: Build JSON Schemas

on:
  push:
    branches:
      - main # Or your default branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Deno
        uses: denoland/setup-deno@11b63cf76cfcafb4e43f97b6cad24d8e8438f62d # v1.5.2
        with:
          deno-version: v1.x # Use the latest stable Deno version or specify one

      - name: Generate JSON Schemas
        run: deno run --allow-read --allow-write --allow-env scripts/generate-json-schema.ts
        env:
          GITHUB_REPO_URL: https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5
        with:
          commit_message: "chore: update generated JSON schemas"
          file_pattern: "*.json" # Commit only JSON files in the root
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com> 
