name: standard
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  standard:
    uses: bounded-systems/.github/.github/workflows/repo-standard.yml@d43c3280588ef05f4ead43426db1091d4cb8f520
    with:
      security: true
      test: true
      runtime: deno
      test-command: "deno fmt --check && deno lint && deno test --allow-all --coverage=cov/ && mkdir -p coverage && deno coverage --lcov cov/ > coverage/cov.lcov && deno check src/mod.ts && deno doc --lint src/mod.ts && deno test --doc --allow-all"
